### ISSUE TITLE
Within a session, participants see the bot's reactions to other participants' prompts

### ISSUE THREAD

**Issue by Howquez** [clintmckenna/oTree_gpt#1]
Hi!

First, thanks a lot -- it's really useful!
Second, there is a problem and I am not sure where to fix it. Maybe you know more:

Assume I have one session with two players, P1 & P2 and P1 communicates with the bot while P2 is silent. Unfortunately, not only P1 sees the bot's reactions but also P2

<img width="1680" alt="Bildschirm­foto 2023-08-12 um 10 09 55" src="https://github.com/clintmckenna/oTree_gpt/assets/19226126/92b9b804-0721-4fc8-be92-75f143fb5912">

As far as I know, this only happens within sessions but not between sessions. I also tried to use two different incognito browsers for P1 and P2... that did not fix the issue.

Best
Hauke

**Comment by clintmckenna** [comment]
Oh, good catch! It looks like this is because I set it to broadcast ChatGPT's message to the whole group, not just the player. In __init__.py, you can change line 187 from this:
`            return {0: output}  
`
to this:
`            return {player.id_in_group: output}  
`

Can you see if this fixes it for you? I'll fix and push an update this week after doing some more testing to make sure this is the problem. I am a little new to using oTree's Live Pages functions!

**Comment by Howquez** [comment]
Same here!

Just implemented it and it seems to work + it makes sense according to the [docs](https://otree.readthedocs.io/en/latest/live.html?highlight=live_method).

Thanks for the quick response.
